"""
Turn every results/<script>.json into LaTeX macros in numbers.tex, so
article.tex quotes only numbers the code actually produced.

Macro naming: results/fit_orbit.json key "sigma_omega_dot_deg_yr" becomes
\\fitorbitSigmaOmegaDotDegYr -- the file stem (lowercased, separators
dropped) followed by the key in CamelCase, with digits spelled out
because LaTeX macro names cannot contain them. Values render with the
format spec stored alongside them (results_io.write_results), or a
4-significant-figure default. Strings pass through verbatim.

Run after every analysis script (run_all.sh does this), then compile.
"""

import glob
import json
import os
import re

RESULTS_DIR = "results"
OUTPUT = "numbers.tex"
DIGIT_WORDS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
               "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def macro_name(stem, key):
    """CamelCase LaTeX-safe macro name from a file stem and a JSON key."""
    parts = re.split(r"[_\-\s]+", key)
    camel = "".join(part[:1].upper() + part[1:] for part in parts if part)
    name = re.sub(r"[^A-Za-z0-9]", "", stem.lower()) + camel
    return "".join(DIGIT_WORDS.get(ch, ch) for ch in name)


def render(entry):
    """Format one JSON entry as the text the macro expands to."""
    value = entry["value"]
    if isinstance(value, str):
        return value
    fmt = entry.get("fmt")
    if fmt is None:
        fmt = ".4g" if isinstance(value, float) else "d"
    text = format(value, fmt)
    if "e" in text and fmt.endswith("e"):
        mantissa, exponent = text.split("e")
        text = f"{mantissa}\\times10^{{{int(exponent)}}}"
    return text


def main():
    """Write numbers.tex from every results/*.json."""
    lines = ["% Generated by make_numbers.py from results/*.json -- do not edit by hand.",
             "% Each macro is a number produced by the named script; regenerate with run_all.sh."]
    count = 0
    for path in sorted(glob.glob(os.path.join(RESULTS_DIR, "*.json"))):
        stem = os.path.splitext(os.path.basename(path))[0]
        with open(path, encoding="utf-8") as handle:
            payload = json.load(handle)
        lines.append(f"% --- {path} ---")
        for key in sorted(payload):
            lines.append(f"\\newcommand{{\\{macro_name(stem, key)}}}{{{render(payload[key])}}}")
            count += 1
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"Wrote {count} macros to {OUTPUT}")


if __name__ == "__main__":
    main()
