"""
Band-integrated relativistic photometry model shared by s301_lightcurve.py
and campaign.py, so the synthetic campaign's photometric channel is
generated by the SAME model the light-curve section validates.

Physics: a blackbody at T_eff, Doppler- and gravitationally-shifted by the
combined factor (1+z) from orbit.redshift_factor, transformed with the
Lorentz-invariant I_nu/nu^3 and integrated over a top-hat K bandpass
matching GRAVITY/VLTI's real operating range (constants.KS_RANGE,
1.98-2.40 um). The delta-magnitude is relative to the median over the
sampled orbit, so it depends only on the shape of the modulation, not on
the star's absolute flux or distance.

Why a shared module: an earlier version of campaign.py generated its
photometry from a bolometric proxy, -2.5*log10((1+z)^-3), whose
peak-to-trough amplitude (0.227 mag) is twice that of the band-integrated
model (0.116 mag) -- at 2.2 um and 7300 K, h*nu/kT ~ 0.9, so the in-band
flux scales roughly as (1+z)^-1.5, not (1+z)^-3. Every downstream
photometric check inherited the wrong amplitude. Generating both from
this one function removes that inconsistency at the source.
"""

import numpy as np

import constants as k


def planck_bnu(freq, temp):
    """Blackbody spectral radiance B_nu(freq, temp)."""
    x = k.h * freq / (k.kB * temp)
    return (2 * k.h * freq ** 3 / k.c ** 2) / np.expm1(x)


def band_flux(one_plus_z, temp=k.T_EFF_K, n_lambda=400):
    """Observed K-band flux (arbitrary units) of a blackbody at `temp`
    seen through a combined redshift factor `one_plus_z` (array), using
    a top-hat transmission over constants.KS_RANGE and the I_nu/nu^3
    beaming relation: I_obs(nu_obs) = I_emit(nu_obs*(1+z)) / (1+z)^3."""
    lam = np.linspace(k.KS_RANGE[0], k.KS_RANGE[1], n_lambda)
    nu_obs = k.c / lam
    one_plus_z = np.atleast_1d(np.asarray(one_plus_z, dtype=float))
    nu_emit = nu_obs[None, :] * one_plus_z[:, None]
    intensity_obs = planck_bnu(nu_emit, temp) / one_plus_z[:, None] ** 3
    return np.abs(np.trapezoid(intensity_obs, nu_obs, axis=1))


_GRID_ONE_PLUS_Z = np.linspace(0.90, 1.10, 2001)
_GRID_LOG_FLUX = np.log10(band_flux(_GRID_ONE_PLUS_Z))


def log10_band_flux(one_plus_z):
    """log10 of band_flux, from a precomputed fine grid in (1+z)
    (interpolation error < 1e-7 mag over S301's actual 0.955-1.025
    range) -- fast enough to call inside a least-squares fit."""
    return np.interp(np.asarray(one_plus_z, dtype=float), _GRID_ONE_PLUS_Z, _GRID_LOG_FLUX)


def dmag_from_one_plus_z(one_plus_z, reference_one_plus_z=None):
    """Delta-magnitude (fainter = positive) relative to the median band
    flux over `reference_one_plus_z` (defaults to `one_plus_z` itself).
    Passing an explicit reference lets a fit evaluate the model at trial
    epochs while keeping the zero point tied to a fixed reference set."""
    log_flux = log10_band_flux(one_plus_z)
    if reference_one_plus_z is None:
        ref = log_flux
    else:
        ref = log10_band_flux(reference_one_plus_z)
    return -2.5 * (log_flux - np.median(ref))
